config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end
  root :to => "posts#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  scope :newest_first, -> { order("posts.created_at DESC") }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:commentary))
    @comment.user_id = current_user.id if current_user
    @comment.save

    if @comment.save
      redirect_to(post_path(@post))
    else
      render('new')
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])   
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id]) 
    
    if @comment.update(params[:comment].permit(:commentary))  
      redirect_to(post_path(@post))
    else
      render('edit')
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to(post_path(@post))
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action(:find_post, :only => [:show, :edit, :update, :destroy])
  before_action(:authenticate_user!, :except => [:index, :show])

  def index
    @posts = Post.newest_first
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create 
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to(@post)
    else
      render('new')
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to(@post)
    else
      render('edit')
    end
  end

  def destroy
    @post.destroy
    redirect_to(root_path)
  end

  private
    def post_params
      params.require(:post).permit(:title, :content)
    end

    def find_post
      @post = Post.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="content">
    <p class="comment_content"><%= comment.commentary %></p>
    <p class="comment_author"><%= comment.user.email %></p>   
  </div>
  <div class="comment_buttons">
    <% if comment.user == current_user %>
      <%= link_to("Edit", edit_post_comment_path(comment.post, comment)) %> 
      <%= link_to("Delete", [comment.post, comment], :method => :delete, :data => { :confirm => "Are you sure?" }) %> 
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
  <%= f.input(:commentary, :label => 'Add a Comment', :placeholder => 'I love Omar!') %>
  <%= f.submit %>
<% end %> 

app/views/comments/edit.html.erb
<h1>Edit your Comment</h1>
<%= simple_form_for([@post, @comment]) do |f| %>
  <%= f.input(:commentary, :label => 'Fix Your Comment') %>
  <%= f.submit %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href: 'http://fonts.googleapis.com/css?family=Ubuntu:300,400,500' rel: 'stylesheet' type: 'text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>  
    <header class="main_header clearfix">
      <div class="wrapper">
        <div id="logo">
          <p><%= link_to("Omar's Forum", root_path) %></p>
        </div>
        <div id="buttons">
          <% if user_signed_in? %>
            <%= link_to("New Post", new_post_path) %>
            <%= link_to("Sign Out", destroy_user_session_path, method: :delete )%>
          <% else %>
            <%= link_to("Sign Up", new_user_registration_path) %>
            <%= link_to("Sign In", new_user_session_path) %>
          <% end %>
        </div>
      </div>
    </header>

    <div class="wrapper">
      <% if user_signed_in? %>
        <div class="currentuser">Signed in as <%= current_user.email %></div>
      <% end %>
    </div>

    <% if notice %>
      <div id="notice_wrapper">
        <p class="notice"><%= notice %></p>
      </div>
    <% elsif alert %>
      <div id="notice_wrapper">
        <p class="alert"><%= alert %></p>     
      </div>  
    <% end %> <br>

    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f|%>
  <%= f.input(:title) %>
  <%= f.input(:content) %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render('form') %>

<%= link_to('Cancel', post_path) %>

app/views/posts/index.html.erb
<div id="posts">
  <% @posts.each do |post| %>
    <div class="post">
      <h2 class="title"><%= link_to(post.title, post) %></h2> 
      <p class="date"><%= "Published #{time_ago_in_words(post.created_at, include_seconds: true)} ago by #{post.user.email}" %></p>   
    </div>
  <% end %> 
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render('form') %>

app/views/posts/show.html.erb
<div id="post_content">
  <h1><%= @post.title %></h1>
  <p><%= @post.content %></p>

  <div id="comments">
    <h2><%= pluralize(@post.comments.count, "Comment") %></h2>
    <%= render(@post.comments) %>

    <% if user_signed_in? %>
      <h3>Reply to this post</h3>
      <%= render("comments/form") %>
    <% else %>    
      <h3>Please Sign in to Reply to this post</h3>
    <% end %>
  </div>
  <% if @post.user == current_user %>
    <br> <hr class="horcol"> <br>
    <%= link_to("Edit", edit_post_path(@post), :class => "button") %>
    <%= link_to("Delete", post_path(@post), :method => :delete, :data => { :confirm => "Are you sure you want to delete this Post?" }, :class => "button") %>
    <%= link_to("Home", root_path, :class => "button") %> 
  <% end %>
</div>